function fname = file_name(station, start_time, end_time)
    fname = sprintf('%s_%02d%02d%02d%02d-%02d%02d%02d%02d.dat', ...
                    station, ...
                    day(start_time), month(start_time), hour(start_time), minute(start_time), ...
                    day(end_time), month(end_time), hour(end_time), minute(end_time));
end